# Generated by Django 2.2.28 on 2023-06-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230610_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.City'),
        ),
    ]
