# Generated by Django 2.2.28 on 2023-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_city_country_region_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
