# Generated by Django 2.2.28 on 2023-07-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('SPAM', 'SPAM'), ('PORNOGRAPHY', 'PORNOGRAPHY'), ('HATRED_AND_BULLING', 'HATRED_AND_BULLING'), ('SELF_HARM', 'SELF_HARM'), ('VIOLENT_GORY_AND_HARMFUL_CONTENT', 'VIOLENT_GORY_AND_HARMFUL_CONTENT'), ('CHILD_PORN', 'CHILD_PORN'), ('ILLEGAL_ACTIVITIES', 'ILLEGAL_ACTIVITIES'), ('DECEPTIVE_CONTENT', 'DECEPTIVE_CONTENT'), ('COPYRIGHT_AND_TRADEMARK_INFRINGEMENT', 'COPYRIGHT_AND_TRADEMARK_INFRINGEMENT'), ('OTHERS', 'OTHERS')], max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
