# Generated by Django 2.2.28 on 2023-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flag',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'SPAM'), ('PORNOGRAPHY', 'PORNOGRAPHY'), ('HATRED_AND_BULLING', 'HATRED_AND_BULLING'), ('SELF_HARM', 'SELF_HARM'), ('VIOLENT_GORY_AND_HARMFUL_CONTENT', 'VIOLENT_GORY_AND_HARMFUL_CONTENT'), ('CHILD_PORN', 'CHILD_PORN'), ('ILLEGAL_ACTIVITIES', 'ILLEGAL_ACTIVITIES'), ('DECEPTIVE_CONTENT', 'DECEPTIVE_CONTENT'), ('COPYRIGHT_AND_TRADEMARK_INFRINGEMENT', 'COPYRIGHT_AND_TRADEMARK_INFRINGEMENT'), ('OTHERS', 'OTHERS')], max_length=200),
        ),
    ]
