# Generated by Django 2.2.28 on 2023-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_read_terms',
            field=models.BooleanField(default=False, verbose_name='Is Read Terms and Condition?'),
        ),
    ]
