# Generated by Django 2.2.28 on 2023-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
