from enum import Enum

class FalgReason(Enum):
    SPAM = "SPAM"
    PORNOGRAPHY = "PORNOGRAPHY"
    HATRED_AND_BULLING = "HATRED_AND_BULLING"
    SELF_HARM = "SELF_HARM"
    VIOLENT_GORY_AND_HARMFUL_CONTENT = "VIOLENT_GORY_AND_HARMFUL_CONTENT"
    CHILD_PORN = "CHILD_PORN"
    ILLEGAL_ACTIVITIES = "ILLEGAL_ACTIVITIES"
    DECEPTIVE_CONTENT = "DECEPTIVE_CONTENT"
    COPYRIGHT_AND_TRADEMARK_INFRINGEMENT = "COPYRIGHT_AND_TRADEMARK_INFRINGEMENT"
    OTHERS = "OTHERS"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)